-- SQL script to add a unique, auto-incrementing student_id column to the public.users table starting from 1000
-- You can run this directly in the SQL Editor of your Supabase Dashboard:

alter table public.users 
add column if not exists student_id int unique generated by default as identity (start with 1000);
